version: '2.7'

rpc:
    listen: tcp://127.0.0.1:6001

reload:
    interval: 5s
    patterns: [ ".php" ]
    dirs: [ "./app/src", "./vendor/spiral/shared" ]
    services:
        http:
            recursive: true
        grpc:
            recursive: true
server:
    command: "php app.php"
    relay: pipes

# serve static files
static:
    dir: "public"

http:
    address: 0.0.0.0:8080
    middleware: [ "gzip", "static" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100

grpc:
    listen: "tcp://0.0.0.0:9001"
    proto:
        - "./vendor/spiral/shared/proto/api/blog/v1/service.proto"
